### ISSUE TITLE
new extension: enx-convert (or maybe enx-events?)

### ISSUE THREAD

**Issue by jacksegal** [c6digital/en-extensions#14]
- Grab from here: https://github.com/c6digital/en-components/blob/main/src/convert.js
- Question is whether this should be just for conversion?  Or whether it should cover other events too?  I think probably just conversion as other events will get too specific to the implementation, so is probably better placed in a theme?  Unless there are other events that we can think of that are "neutral" like conversion... (ga4 / capi stuff?  but that feels like theme to me...)
- We should also do some work on the groups (added all page types to bottom)

pageType:

- advocacypetition
- click2call
- datacapture
- donation
- e-card
- e-commerce
- event
- emailsubscribeform
- emailtotarget
- membership
- peer-to-peerevent
- premiumgift
- splitpage
- staticpage
- supporterhub
- survey
- tweetpage
- unsubscribe

**Comment by MichaelT372** [comment]
enx-convert has been added!
